format_version: 10
pipelines:
  Game-2048:
    group: demo
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-3a60873:
        git: https://github.com/Gabriel-cxa/docker-2048.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build-image:
            timeout: 0
            tasks:
            - plugin:
                configuration:
                  id: script-executor
                  version: 0.3.0
                options:
                  script: |-
                    aws ecr get-login-password --region cn-northwest-1 | docker login --username AWS --password-stdin 723282842938.dkr.ecr.cn-northwest-1.amazonaws.com.cn
                    docker build -t 723282842938.dkr.ecr.cn-northwest-1.amazonaws.com.cn/game2048:latest --force-rm .
                    docker push 723282842938.dkr.ecr.cn-northwest-1.amazonaws.com.cn/game2048:latest
                  shtype: bash
                run_if: passed