environments:
  cxa-infra:
    environment_variables:
      # AWS ECR
      AWS_ECR_REGISTRY_NAME: "285584781843.dkr.ecr.ap-southeast-1.amazonaws.com"
      CLOUD_PROVIDER: "aws"
      MESSAGE_QUEUE_PROVIDER: "STAN"
      KUBERNETES_TYPE: "eks"
      KUBECONFIG_CLUSTER_NAME: "cxa-infra-cluster"
      KUBECONFIG: "/var/go/.kube/config-cxa-infra"
      KUBECONFIG_CLUSTER_CA_CERT: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01ETXhPVEV5TlRVeE5Wb1hEVE13TURNeE56RXlOVFV4TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSnBNCjNIR0JLUFJPL3hDbVNHaEhzd1p5Z0hSMThVQjAwYzZFaFJJR1A5VmJseGl0eFZ0Nk95RFFQaXRBR0gveDNwRFoKUHE4Ti96dWs2RTJ6bGdJWFNISXRtSG5EQTNVRFBNclYyQ0JSYlNZSm53NitpV3lXc3g0eGxiVnBNOWhUTHRrMwpUQ2FnUG5SaVpjSndNQkxiOUZpNG1OWHZ6U2J3ZnQrb2VUNkNjRHJzSXZPWEh0TFdnM3pscm9FSnhsV1lrWkpiCjVzK2VldUtBY1FOMEE0MjJQbFZpS3AwSG1XVklUcC85SFJQM2Q5bUh4NFQ1UUM3eGxPVHNNTngrM1BMYjdmVzQKdXZ0aUR2Z3ZLZ0tZMTJVM1hmWkdzY3ZJeWJHS0U0bDhPSFZ1SFE1RzBCVVZ3RGp4Y05XczRMUkJKN0FMV2FrVwpoMG45RGV5QWJWWFZ2RUt4RllFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCcGZtN0R1R3kzWVpGODY2WVloTXBNUW92UFUKbUdrYStCT3ZzMEUrS0RtMVZ5VlI0MlZ1MnZYV0Fxc1BJV0o2ZmlXZFJjS1pQUElYR2c5WVFKVWxycXhTU3NTYgpHa1hTRXQ3cC9yRzljb2hYbGgwaXJIZVc5b0VvUGxxakhBeXFDb3A2VlRiU2tiYzN2Zkt3akgrQ1RjSzduVkpKCjhrYWRiSHdobkg0TzFLSGhWdEdxUDdKbjUyL0xLMXAwVzhjVG5WSkI4U0J6QmFwUHVqdngxd3JjVGJjRklpeWIKK0ZvRmxCemRBUXAyUjV3MG5ZMkx4bExzVFhRZmk0akpRcGJFM2h5TldKR3pKYzhVQ2NHUDdFQWxzQjIvTHVpKwpiUWtIY0VNOHorWGcxS1BNYUVTc3k1SWgyQnVvdHR0a2NPd0dOc2ZZK2V2OERLYVZNTUFDc25rTkxxND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      KUBECONFIG_CLUSTER_SERVER: "https://2479A31C38E10A7517B0162302FA2271.gr7.ap-southeast-1.eks.amazonaws.com"
      KUBECONFIG_USER_NAME: "eks-ci-user"
      KUBECONFIG_USER_CERT: ""
      KUBECONFIG_CONTEXT_NAME: "cxa-infra"
      ECR_REGISTRY: "285584781843.dkr.ecr.ap-southeast-1.amazonaws.com"
      # infra
      VAULT_ADDR: "https://vault.cxanow.com"


      QA_EMAIL_REPORT_SMTP_SERVER: "smtp.office365.com"
      QA_EMAIL_REPORT_SMTP_PORT: "587"
      QA_EMAIL_REPORT_SMTP_USER: "infra.notifications@cxagroup.com"
      #Sonatype Nexus
      NEXUS_INTERNAL_URL: "https://repository.cxanow.com"
      NEXUS_EXTERNAL_URL: "https://repository.cxanow.com"

    secure_variables:
      KUBECONFIG_USER_KEY: "AES:J1m83znoUVIqnctE5T8B6w==:dUWZNjrel0eUmb4LBEol5c8xHe8FB5cd78eyD5e6cPq16Fwry1huMxUn7Y8XTiTtUUnDwqhoYVHEIy13EKdAcMsWXaTY1PFVqs2tIMn4R0E3O6annF9nJoR8X4vGT1+ALKeyQbr1Y1gkOycyCzDIFWv0qvUgTLGv0q1MVJOF65Uwn9bMz8PKEqskWulJ44V5q1nxZH4/cQnpXOpDyokGpDZS1kOV/K4jxm2Hjj+6Pr+Dj7zYJCRMU8cVuBAgjx62u2e4If4azGD8Ht6sHsCSWn2PiAywOjZi43yp8y7G/2GB+t2+rk0HK/7xxow2bU2MulW7zmFF8uckrtyEcCaVI4TRtnzimEWaTPWMErFm2KkZn5isE28fJwSMPpm2TpX6D5I4R86SCr/Ux8rlcaPMCaE1lad4UYuOaamupGPkSLMzAmUr2umwIFJgERuBVjzshfcLHICSDfyi4Q/TqfFScIFsBFWPvEnSYFP31I8r6aGWIjIATddpbR2xSDOCNdgCM8+WYGGKlYKXcFZJEXGp9XeCP5gnOuNzIQ3HuCUkZfzjwWF0ywPUiaq1Mpt6wYTzY1fhjInACmhAJEuKRO5TjQqoP4jYiJWZGP8J0JU1e45mMi/HoV07IzAy/Znd5hMEgSHr+NSutaAGEjB/1/IqSNPRjGk9F0fb9R/e1KwB9sWz39c1g1QEFmcc07s1MHnK/u2UXHAjk2ETONrKBBpJRIpqL8VLg+eRG2xgAk8oUgz0dbXnzzybUH0Y59ug9PIkpTJiMdAdXWzYWOe0fzfPi2DSbY6N+i/6ueW7PAE0lwpNKwa/Ap7zR19Xx7A0p5vL8ra7LsWVqGepRPPGSFY4Upkn7bQQE+cwOchZbuuzY4UjCf7FQj5FENNH/ZUpc3PpK75pSlrzZC84YdvZn+api1osVBMLhySslj2Hra9KwrbtgjQC+oAVanOsqkBBb7paYE2mLHQiDUHGus1FmvrpMqIgpuk5i6JcbI//OwACPONHAFeg9ydWzP10/3/z7H9u2cNCxmHHQ68hZMk+s/xz1yjQ/Kw/CVlnBp0F/B5YdFJib2zrCnVR3vPoBKWBoKhthcjj1bH8h6+VRuBs6vCkazEwNUCRJ9wd/vwiNIjFsN1lkcl9AQmmPvy2Q4kYqi8Jw4YvJW/6gI90tw2vJ729xQ0NGPNjMjKERnjgwLf528/aT7VlwPYqEZfRZ/1HsKhUe/fmLtoZsgy/3p2xSON6dw=="
      GOCD_ADMIN_TOKEN: "AES:q8fvv4K6ds6ClKbTs1mI0g==:S0vPyhsu85IAWRi1yOcSqwvFSB4ZTDuP2mdTFnriuFbJ2Gq1oUh2o0scHfY6Gcj6"


      QA_EMAIL_REPORT_SMTP_PASSWORD: "AES:B3/njpIEbFjkIVIxUgAibg==:foDPP7xMVcdI1opfa62/Gg=="
      JIRA_GOCD_AUTH_TOKEN: "AES:b2ElY1lAriKxxWnNEqc6/w==:7ucB2t4s8GuJbi51P2qSxUUZwBXxyPHTgwCUrkOH/IqUOzMtzbW2kmqNXDHXUqjs"
