environments:
  infra-common:
    environment_variables:
      AWS_ECR_REGISTRY_NAME: "285584781843.dkr.ecr.ap-southeast-1.amazonaws.com"
      REPO_USERNAME: "ci-user"
      SENTRY_ENV: "cxa-development"
      SENTRY_ORG: "cxa-group-pte-ltd"
      SENTRY_PROJECT: "distribution-employee-frontend"
      MAGENTO_REPO_USERNAME: "c302d604b9ee3ef5b55c2ade806d9846"
      NEXUS_INTERNAL_URL: "https://repository.cxanow.com"

      INFRA_VALIDATE_SSL_FOR_DOMAINS_CSV: "cxaben.cxagroup.com, ds.cxagroup.com, ecommerce2-api.cxagroup.com, assets.cxagroup.com, cxaonedemo.com, cxaonedev1.com, cxaonetest2.com, cxaoneuat1.com, cxaoneuat2.com, cxaoneuat3.com, benefitsplus-auth-uat.hsbc.com.hk, employeebenefits-uat.hsbc.com.hk, benefitsplus-choices-uat.hsbc.com.hk,benefitsplus-distribution-platform-uat.hsbc.com.hk, cxapalawanuat.com, cxapalawanstaging.com, cxapalawan.com, repository.cxanow.com"

      # infra
      VAULT_ADDR: https://vault.cxanow.com

    secure_variables:
      NPM_REGISTRY_TOKEN: "AES:et1j3nNNwq4kdXVtYjzapA==:DqIuZ1PU05CYURdZqpP88eWrIFmWlCQ0NsLInyC1uv2Gi+3XtGxT35Uaxdz9aLbj"
      REPO_PASSWORD: "AES:BlBev5AtDAv0t9udM2pYOQ==:lDxSbVRGHmfuHP+H/8ijxE60OT4CGJvdT6vYhyPSPcY="
      SENTRY_DSN: "AES:ol4iAFVrM/aRmOHMm0HEew==:NSc2M20ujcQR55SJZhOG/puPLvTUcMYNgMIzELqF4pNLuJpew5zyXkgY+evuak4oseCoVIhnhqzLZPQsjSUkbg=="
      CS_SENTRY_DSN: "AES:jim9+QnwvWo6idUsfPuznA==:HJKL4W++zf/DtvI9ZpuCe4WrLe8nw1GNotosiwRm5nlJ33Dm/0z0TZYxs0QyZ0Gw64Y4FwCqkPyTRnJh3nAcDtvvPaeXPfC3DH5YHbBDlg4="
      SENTRY_AUTH_TOKEN: "AES:A45dEwfWvqlupjf6RqjAMA==:w7ccWG4h7tbiJXpX1zw7wJS38HlqjmJj/g6wlZhqazBUQphFIIr4e/JaDc0mLwM4nY2MVLpUiW8f+BjYT3laGnQFSsIXtCgsKoekEts1CXQ="
      MAGENTO_REPO_PASSWORD: "AES:QRIXu0WejR6M+FVO123pew==:1N53n3ZWk1rq25f5qwVWQcsLtx4p+/QPdiaKb9JD0v1udC1jYY2nlRK+g+vBBqzc"
      SLACK_WEBHOOK_URL: "AES:x+XOfF2Wxzw9nZZVmtw/QQ==:iOLPZ419zNzbgxqz4ZLIDuG2ukjn0isOFv27INpY7H53X9SirGo3zyNJcVNeioKOGWvqmTGPbdI5LeTNYbfIwH1LpiLlep1GpPzkxvkwUZM="

      INFRA_ALERTS_SLACK_INFRACHANNEL_WEBHOOK_URL: "AES:LlXZ5jY1tfzaV6pNe0JkCQ==:q4e7lDwmO5kmdVYnIuDQN2BgpUgeLDg5ofatu7xf/Hwqb31nPtC9IC9cXL2Za2SqLWa+q3xvmhx5cottdKs7g1A5hahK4AMb6U7b8uKYBIo="

    pipelines:
      - infrastructure_validate-ssl-cert
      # Ansible managed
      - distribution-member-job_build
      - distribution-member-job_build-R4B
      - distribution-auth-listener_build
      - distribution-auth-listener_build-R4B
      - distribution-claim-job_build
      - distribution-claim-job_build-R4B
      - distribution-member-listener_build
      - distribution-member-listener_build-R4B
      - distribution-ewallet-listener_build
      - distribution-ewallet-listener_build-R4B
      - distribution-benefit-listener_build
      - distribution-benefit-listener_build-R4B
      - distribution-notification-listener_build
      - distribution-notification-listener_build-R4B
      - distribution-admin-portal_build
      - distribution-admin-portal_build-R4B
      - distribution-employee-frontend_build
      - distribution-employee-frontend_build-R4B
      - distribution-identity-service_build
      - distribution-identity-service_build-R4B
      - distribution-admin-service_build
      - distribution-admin-service_build-R4B
      - distribution-auth-service_build
      - distribution-auth-service_build-R4B
      - distribution-benefit-service_build
      - distribution-benefit-service_build-R4B
      - distribution-claim-service_build
      - distribution-claim-service_build-R4B
      - distribution-member-service_build
      - distribution-member-service_build-R4B
      - distribution-notification-service_build
      - distribution-notification-service_build-R4B
      - distribution-wellness-service_build
      - distribution-wellness-service_build-R4B
      - distribution-recommendation-service_build
      - distribution-recommendation-service_build-R4B
      - distribution-ewallet-service_build
      - distribution-ewallet-service_build-R4B
      - distribution-payment-service_build
      - distribution-payment-service_build-R4B
      - distribution-wallet-job_build
      - distribution-wallet-job_build-R4B
      - distribution-benefit-job_build
      - distribution-benefit-job_build-R4B
      - distribution-wallet-listener_build
      - distribution-wallet-listener_build-R4B
      - distribution-wellness-listener_build
      - distribution-wellness-listener_build-R4B
      - distribution-claimfeed-listener_build
      - distribution-claimfeed-listener_build-R4B
      - distribution-panel-service_build-R4B
      - distribution-wallet-service_build
      - distribution-wallet-service_build-R4B
      - distribution-claim-integration_build
      - distribution-claim-integration_build-R4B
      - distribution-partner-api-mockup_build
      - distribution-partner-api-mockup_build-R4B
      - distribution-panel-job_build-R4B
      - distribution-payment-job_build
      - distribution-payment-job_build-R4B
      - distribution-client-service_build
      - distribution-client-service_build-R4B
      - distribution-etpa-service_build
      - distribution-etpa-service_build-R4B
      - distribution-etpa-job_build
      - distribution-etpa-job_build-R4B
      - distribution-shop-service_build
      - distribution-cms-portal_build
      - distribution-cms-portal_build-R4B
      - distribution-camel-notification-service_build
      - distribution-camel-notification-service_build-R4B
      - distribution-wellness-job_build
      - distribution-auth-cognito-service_build
      - distribution-shop-vanilla-pwa_build
      - distribution-function-dispatcher_build
